sudo: false
before_install:
    - wget https://matrix.org/git/olm/snapshot/olm-2.2.0.tar.bz2
    - tar -xvf olm-2.2.0.tar.bz2
    - pushd olm-2.2.0 && make && sudo make PREFIX="/usr" install && popd
    - rm -r olm-2.2.0
language: python
python:
  - "2.7"
  - "3.6"
install: pip install tox-travis
script: tox
